on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Build deps
      run: |  
        sudo apt update
        sudo apt install llvm llvm-dev
        wget https://releases.llvm.org/9.0.0/llvm-9.0.0.src.tar.xz
        tar -xf llvm-9.0.0.src.tar.xz 
        cd llvm-9.0.0.src
        mkdir -p build
        cd build
        cmake ..
    - name: Build C Code
      run: |         
        ./configure
        make
